"""
F1 Points Engine — FastAPI Application
========================================
Main entry point for the backend API server.

Endpoints:
- REST API at /api/*
- API docs at /docs (auto-generated by FastAPI)
- Static files at / (serves React app in production when frontend/dist/ exists)
"""

import logging
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

from backend.db.database import init_db
from backend.api.routes import drivers, constructors, races, team, points, chips, standings, transfers, simulator, sync

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

# Path to the built React app — present in production after build.sh runs
_HERE = Path(__file__).parent.parent  # repo root
STATIC_DIR = _HERE / "frontend" / "dist"


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown events."""
    logger.info("Starting F1 Points Engine backend...")
    init_db()
    if STATIC_DIR.exists():
        logger.info("Production mode: serving React app from %s", STATIC_DIR)
    else:
        logger.info("Development mode: no static frontend found at %s", STATIC_DIR)
    yield
    logger.info("F1 Points Engine backend shut down.")


app = FastAPI(
    title="F1 Points Engine API",
    description="Fantasy F1 scoring engine with chip advisor",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://f1.job-joseph.com",
        "http://localhost:5173",
        "http://localhost:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- API routes (registered first so /api/* is never caught by static) -------
app.include_router(drivers.router)
app.include_router(constructors.router)
app.include_router(races.router)
app.include_router(team.router)
app.include_router(points.router)
app.include_router(chips.router)
app.include_router(standings.router)
app.include_router(transfers.router)
app.include_router(simulator.router)
app.include_router(sync.router)


@app.get("/health")
async def health():
    return {"status": "ok"}


# --- Static file serving (production only) -----------------------------------
# Mounted AFTER all API routes so /api/* is never swallowed by the catch-all.
# In development (no dist/ directory) this block is skipped entirely.
if STATIC_DIR.exists():
    assets_dir = STATIC_DIR / "assets"
    if assets_dir.exists():
        app.mount("/assets", StaticFiles(directory=str(assets_dir)), name="assets")

    @app.get("/{full_path:path}", include_in_schema=False)
    async def serve_spa(full_path: str):
        """
        Catch-all for client-side routing: return index.html for any path
        not matched by an API route or the /assets mount above.
        """
        requested = STATIC_DIR / full_path
        if requested.is_file():
            return FileResponse(str(requested))
        return FileResponse(str(STATIC_DIR / "index.html"))
else:
    @app.get("/")
    async def root():
        return {"message": "F1 Points Engine API v1.0", "docs": "/docs"}
