"""
F1 Points Engine — FastAPI Application
========================================
Main entry point for the backend API server.

Endpoints:
- REST API at /api/*
- WebSocket at /ws/live (live race point updates every 30s)
- API docs at /docs (auto-generated by FastAPI)
"""

import json
import logging
from contextlib import asynccontextmanager
from typing import Any

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware

from backend.db.database import init_db
from backend.scheduler.live_poller import start_scheduler, stop_scheduler, set_connection_manager
from backend.api.routes import drivers, constructors, races, team, points, chips, live, standings, validation

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)


class ConnectionManager:
    """Manages WebSocket connections for live race updates."""

    def __init__(self):
        self.active_connections: list[WebSocket] = []

    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
        logger.info("WebSocket client connected. Total: %d", len(self.active_connections))

    def disconnect(self, websocket: WebSocket):
        self.active_connections.remove(websocket)
        logger.info("WebSocket client disconnected. Total: %d", len(self.active_connections))

    async def broadcast(self, data: Any):
        """Broadcast data to all connected clients. Remove dead connections."""
        message = json.dumps(data)
        dead = []
        for ws in self.active_connections:
            try:
                await ws.send_text(message)
            except Exception:
                dead.append(ws)
        for ws in dead:
            self.active_connections.remove(ws)


manager = ConnectionManager()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup and shutdown events."""
    logger.info("Starting F1 Points Engine backend...")
    init_db()
    set_connection_manager(manager)
    start_scheduler()
    yield
    stop_scheduler()
    logger.info("F1 Points Engine backend shut down.")


app = FastAPI(
    title="F1 Points Engine API",
    description="Fantasy F1 scoring engine with live race tracking and chip advisor",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000", "*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register all API routers
app.include_router(drivers.router)
app.include_router(constructors.router)
app.include_router(races.router)
app.include_router(team.router)
app.include_router(points.router)
app.include_router(chips.router)
app.include_router(live.router)
app.include_router(standings.router)
app.include_router(validation.router)


@app.get("/")
async def root():
    return {"message": "F1 Points Engine API v1.0", "docs": "/docs"}


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.websocket("/ws/live")
async def websocket_live(websocket: WebSocket):
    """
    WebSocket endpoint for live race point updates.
    Pushes full driver/constructor fantasy points breakdown every 30 seconds.
    """
    await manager.connect(websocket)
    try:
        while True:
            # Keep connection alive; actual data is pushed by the poller
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(websocket)
